### ISSUE TITLE
See a goal description

### ISSUE THREAD

**Issue by WouterKvG** [feedbackfruits/bepstore-ui#5]

**Comment by WouterKvG** [comment]
@bartist What fields should be present in api-goals? I got title and description right now.

**Comment by bartist** [comment]
A goal should have a id, title, description, Product Owner, Head Design, Head Front-End and Head Back-end.
A goal should have multiple updates (status & what is next, see goal/x/descr)
If you look at utils/mockMaker in ui, you can get a impression
